export const Copyrights = [
  "inquirer.net",
  "mb.com.ph",
  "newsbreak.com",
  "manilatimes.net",
  "gmanetwork.com",
  "abs-cbn.com",
  "pna.gov.ph",
  "sunstar.com.ph",
  "businessmirror.com.ph",
  "rappler.com",
  "bworldonline.com",
  "philnews.ph",
  "malaya.com.ph",
  "philstar.com",
  "spin.ph",
  "thefinancialdistrict.com.ph",
  "newspapers.ph",
  "pageone.ph",
  "senate.gov.ph",
  "lionheartv.net",
  "philippinetimes.com",
  "punto.com.ph",
  "villagepipol.com",
  "manilametro.com",
  "orangemagazine.ph",
  "adobomagazine.com",
  "visayandailystar.com",
  "palawan-news.com",
  "abante.com.ph",
  "esquiremag.ph",
  "licas.news",
  "starmometer.com",
  "tiebreakertimes.com.ph",
  "manilashaker.com",
  "tempo.com.ph",
  "wheninmanila.com",
  "candymag.com",
  "manilarepublic.com",
  "mims.com",
  "topgear.com.ph",
  "cnnphilippines.com",
  "eaglenews.ph",
  "noypigeeks.com",
  "theglobalfilipinomagazine.com",
  "wethepvblic.com",
  "worldweeklynews.com",
  "2ndopinion.ph",
  "8list.ph",
  "autodeal.com.ph",
  "carguide.ph",
  "latestchika.com",
  "newsbytes.ph",
  "philkotse.com",
  "preview.ph",
  "spot.ph",
  "canberranews.net",
  "technobaboy.com",
  "autocar.com.ph",
  "gadgetpilipinas.net",
  "gadgetsmagazine.com.ph",
  "goodnewspilipinas.com",
  "journal.com.ph",
  "mindanews.com",
  "singaporestar.com",
  "sugbo.ph",
  "thedailyguardian.net",
  "yehey.com",
  "aseanmp.org",
  "boholchronicle.com.ph",
  "bomboradyo.com",
  "cakafete.com",
  "cbcpnews.net",
  "cmfr-phil.org",
  "gamingph.com",
  "nolisoli.ph",
  "outoftownblog.com",
  "pba.ph",
  "pep.ph",
  "pinoymetrogeek.com",
  "revu.com.ph",
  "rmn.ph",
  "shangbao.com.ph",
  "smartparenting.com.ph",
  "techpinas.com",
  "theappwhisperer.com",
  "thesummitexpress.com",
  "ungeek.ph",
];

export const catList = [
  {
    value: "",
    label: "All",
  },
  {
    value: "news",
    label: "news",
  },
  {
    value: "sport",
    label: "sport",
  },
  {
    value: "tech",
    label: "tech",
  },
  {
    value: "world",
    label: "world",
  },
  {
    value: "finance",
    label: "finance",
  },
  {
    value: "politics",
    label: "politics",
  },
  {
    value: "business",
    label: "business",
  },
  {
    value: "economics",
    label: "economics",
  },
  {
    value: "entertainment",
    label: "entertainment",
  },
  {
    value: "beauty",
    label: "beauty",
  },
  {
    value: "travel",
    label: "travel",
  },
  {
    value: "music",
    label: "music",
  },
  {
    value: "food",
    label: "food",
  },
  {
    value: "science",
    label: "science",
  },
  {
    value: "gaming",
    label: "gaming",
  },
];
