export const NewsData = [
    {
        id: 1,
        title:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis itaque quos laboriosam qui nisi nostrum hic, tempora soluta magni nam. ",
        story:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sagittis neque vel tristique tempor. Etiam interdum mi urna, et finibus ligula semper in. Ut a diam a sem volutpat gravida. Cras orci dolor, iaculis sit amet tortor at, fringilla dapibus quam. Duis consectetur magna a metus commodo vestibulum. Phasellus non ligula velit. Praesent a velit orci. Phasellus non commodo odio. Phasellus vitae velit neque. Nunc sollicitudin dui ante, id dapibus nulla venenatis sed. Suspendisse potenti. Nulla tincidunt metus eget elit commodo venenatis.  Suspendisse porttitor facilisis leo ac maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In vitae odio hendrerit quam pharetra euismod. Etiam accumsan lectus eget diam finibus cursus. Nam quis interdum sem. Duis ac consectetur tellus. Suspendisse tempor vitae tortor eget fringilla.Quisque ipsum lorem, fringilla a mollis nec, auctor quis magna. Mauris tincidunt tellus lacus, in interdum justo scelerisque id. Integer vitae efficitur diam. Curabitur venenatis auctor pretium. Suspendisse mattis sed nibh euismod pellentesque. Maecenas vulputate pellentesque nunc in varius. Maecenas nec felis cursus, maximus dui a, sagittis mauris. Morbi consequat dignissim erat, ultrices gravida lectus.",
        categories: "Business",
        date: "Aug 8 2022 Tue",
        author: "Ezio Auditore",
        image:
            "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
    },
    {
        id: 2,
        title:
            "    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis itaque quos laboriosam qui nisi nostrum hic, tempora soluta magni nam.        ",
        story:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sagittis neque vel tristique tempor. Etiam interdum mi urna, et finibus ligula semper in. Ut a diam a sem volutpat gravida. Cras orci dolor, iaculis sit amet tortor at, fringilla dapibus quam. Duis consectetur magna a metus commodo vestibulum. Phasellus non ligula velit. Praesent a velit orci. Phasellus non commodo odio. Phasellus vitae velit neque. Nunc sollicitudin dui ante, id dapibus nulla venenatis sed. Suspendisse potenti. Nulla tincidunt metus eget elit commodo venenatis.",
        categories: "Sports",
        date: "Aug 8 2022 Tue",
        author: "Mark Angelo Ignacio",
        image:
            "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
    },
    {
        id: 3,
        title:
            "    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis itaque quos laboriosam qui nisi nostrum hic, tempora soluta magni nam.        ",
        story:
            "    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum nesciunt modi deserunt eum quia ratione ipsum a optio sapiente corrupti recusandae animi aperiam beatae, dolorum, quasi ea tempore harum iusto voluptas molestiae fugit dolorem? Ex ut corporis quaerat deleniti delectus quidem, dolore inventore? Sed, iste! Velit quas voluptate dolore atque earum neque, laudantium sed aut nemo ullam, illum fuga dicta animi a sint rerum! Ipsa sed quod officiis quasi rem a eligendi vitae illo possimus optio excepturi suscipit sit soluta praesentium provident, dolor perspiciatis rerum. Eveniet eaque dolor officia error libero, mollitia soluta. Suscipit nesciunt ex ea reiciendis eaque repudiandae.",
        categories: "Sports",
        date: "Aug 8 2022 Tue",
        author: "Ezio Auditore",
        image:
            "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
    },
    {
        id: 4,
        title:
            "    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis itaque quos laboriosam qui nisi nostrum hic, tempora soluta magni nam.        ",
        story:
            "    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum nesciunt modi deserunt eum quia ratione ipsum a optio sapiente corrupti recusandae animi aperiam beatae, dolorum, quasi ea tempore harum iusto voluptas molestiae fugit dolorem? Ex ut corporis quaerat deleniti delectus quidem, dolore inventore? Sed, iste! Velit quas voluptate dolore atque earum neque, laudantium sed aut nemo ullam, illum fuga dicta animi a sint rerum! Ipsa sed quod officiis quasi rem a eligendi vitae illo possimus optio excepturi suscipit sit soluta praesentium provident, dolor perspiciatis rerum. Eveniet eaque dolor officia error libero, mollitia soluta. Suscipit nesciunt ex ea reiciendis eaque repudiandae.        ",
        categories: "Sports",
        date: "Aug 8 2022 Tue",
        author: "Ezio Auditore",
        image:
            "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
    },
    {
        id: 5,
        title:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis itaque quos laboriosam qui nisi nostrum hic, tempora soluta magni nam.       ",
        story:
            "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum nesciunt modi deserunt eum quia ratione ipsum a optio sapiente corrupti recusandae animi aperiam beatae, dolorum, quasi ea tempore harum iusto voluptas molestiae fugit dolorem? Ex ut corporis quaerat deleniti delectus quidem, dolore inventore? Sed, iste! Velit quas voluptate dolore atque earum neque, laudantium sed aut nemo ullam, illum fuga dicta animi a sint rerum! Ipsa sed quod officiis quasi rem a eligendi vitae illo possimus optio excepturi suscipit sit soluta praesentium provident, dolor perspiciatis rerum. Eveniet eaque dolor officia error libero, mollitia soluta. Suscipit nesciunt ex ea reiciendis eaque repudiandae.        ",
        categories: "Sports",
        date: "Aug 8 2022 Tue",
        author: "Ezio Auditore",
        image:
            "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
    },
];

export const RecentData = [
    {
        id: 1,
        categories: "news",
        title: "Lorem Ipsum",
    },
    {
        id: 2,
        categories: "sport",
        title: "Lorem Ipsum",
    },
    {
        id: 3,
        categories: "tech",
        title: "Lorem Ipsum",
    },
    {
        id: 4,
        categories: "world",
        title: "Lorem Ipsum",
    },
    {
        id: 5,
        categories: "finance",
        title: "Lorem Ipsum",
    },
    {
        id: 6,
        categories: "politics",
        title: "Lorem Ipsum",
    },
    {
        id: 7,
        categories: "business",
        title: "Lorem Ipsum",
    },
    {
        id: 8,
        categories: "economics",
        title: "Lorem Ipsum",
    },
    {
        id: 9,
        categories: "entertainment",
        title: "Lorem Ipsum",
    },
    {
        id: 10,
        categories: "beauty",
        title: "Lorem Ipsum",
    },
    {
        id: 11,
        categories: "travel",
        title: "Lorem Ipsum",
    },
    {
        id: 12,
        categories: "music",
        title: "Lorem Ipsum",
    },
    {
        id: 13,
        categories: "food",
        title: "Lorem Ipsum",
    },
    {
        id: 14,
        categories: "science",
        title: "Lorem Ipsum",
    },
    {
        id: 15,
        categories: "gaming",
        title: "Lorem Ipsum",
    },
];

export const SourcesData = {
    "status": "ok",
    "total_hits": 10000,
    "page": 1,
    "total_pages": 200,
    "page_size": 50,
    "articles": [
        {
            "title": "Coco Martin chosen to continue legacy of Susan Roces",
            "author": "Manila Bulletin Entertainment",
            "published_date": "2023-01-27 03:13:28",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/coco-martin-chosen-to-continue-legacy-of-susan-roces/",
            "clean_url": "mb.com.ph",
            "excerpt": "Coco Martin The country's leading pharmaceutical brand RiteMed has officially unveiled its new brand ambassador with the launch of its latest TV commercial (TVC) featuring the well-loved and highly…",
            "summary": "Coco Martin\nThe country's leading pharmaceutical brand RiteMed has officially unveiled its new brand ambassador with the launch of its latest TV commercial (TVC) featuring the well-loved and highly respected actor-director Coco Martin.\nCoco graciously accepted the challenge of continuing the legacy and advocacy of the Queen of Philippine Movies, Ms. Susan Roces, of empowering the masses in opting for quality and affordable healthcare.\nCoco rightfully opened the TVC with the line 'Ang sabi ng lola ko, ‘wag mahihiyang magtanong…at hanapin ang check', which not only gives honor to Ms.",
            "rights": "",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Manila Bulletin Entertainment",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/DSC00019-1024x683.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "0d0cfc1b290fe7a0ca46f5e4ac552475"
        },
        {
            "title": "Balitanghali Livestream: January 27, 2023",
            "author": "GMA News Online",
            "published_date": "2023-01-27 03:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.gmanetwork.com/news/video/balitanghali/614188/balitanghali-livestream-january-27-2023/video/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Balitanghali is a noontime GMA Network newscast, anchored by Raffy Tima and Connie Sison. It airs on GTV Mondays to Fridays at 11:00 AM (PHL Time). For more videos from Balitanghali, visit…",
            "summary": "We use cookies to ensure you get the best browsing experience. By continued use, you agree to our privacy policy and accept our use of such cookies. For further information, click FIND OUT MORE.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "GMA News Online",
            "media": "https://i3.ytimg.com/vi/PGPqzfefzyA/0.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "a7de43d716b6a34b078ad6de4253c0cd"
        },
        {
            "title": "Marcos invited to UK for King Charles' coronation",
            "author": "Joseph Pedrajas",
            "published_date": "2023-01-27 02:53:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/marcos-invited-to-uk-for-king-charles-coronation/",
            "clean_url": "mb.com.ph",
            "excerpt": "President Ferdinand 'Bongbong' Marcos Jr. has been invited to go to the United Kingdom for His Majesty King Charles III's coronation.\n\r\rThis was bared by UK Ambassador to the Philippine Laure Beaufils, who said Marcos will be getting an invitation anytime soon.\n\r\r'We've already sent him the 'save th",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\nPresident Ferdinand 'Bongbong' Marcos Jr. has been invited to go to the United Kingdom for His Majesty King Charles III's coronation.\nThis was bared by UK Ambassador to the Philippine Laure Beaufils, who said Marcos will be getting an invitation anytime soon.\n'We've already sent him the ‘save the date',' Beaufils said in an interview with CNN Philippines on Thursday night.\nThe diplomat said Marcos has the option to go or not, but UK 'wants to see' him there.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Joseph Pedrajas",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122462.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "3ebc670f31e19bdf93e034c82ce83a5d"
        },
        {
            "title": "ICC orders resumption of probe into PH 'drug war'",
            "author": "Christian Crow Maghanoy",
            "published_date": "2023-01-27 02:52:17",
            "published_date_precision": "full",
            "link": "https://www.manilatimes.net/2023/01/27/news/icc-orders-resumption-of-probe-into-ph-drug-war/1876095",
            "clean_url": "manilatimes.net",
            "excerpt": "THE International Criminal Court's (ICC) pre-trial chamber has granted the prosecutor's request to resume the investigation on the drug war in the Philippines, saying it...",
            "summary": "THE International Criminal Court's (ICC) pre-trial chamber has granted the prosecutor's request to resume the investigation on the drug war in the Philippines, saying it was \"not satisfied\" with the information provided by the government that could have warranted a deferment of its order.\"After having examined the submissions and materials of the Philippine Government and of the ICC Prosecutor as well as the victims' observations, the Chamber concluded that the various domestic initiatives and proceedings, assessed collectively, do not amount to tangible, concrete and progressive investigative steps in a way that would sufficiently mirror the Court's investigation,\" the chamber's statement read.",
            "rights": "manilatimes.net",
            "rank": 7400,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Christian Crow Maghanoy",
            "media": "https://www.manilatimes.net/manilatimes/uploads/images/2023/01/27/152045.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "c4828fca98b8234df6977bc1b15075a0"
        },
        {
            "title": "Lito Lapid praises Coco Martin for giving respect to jobless, veteran stars",
            "author": "Robert Requintina",
            "published_date": "2023-01-27 02:39:42",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/lito-lapid-praises-coco-martin-for-giving-respect-to-jobless-veteran-stars/",
            "clean_url": "mb.com.ph",
            "excerpt": "Sen. Lito Lapid (Facebook) Senator Lito Lapid announced his return to primetime television with Coco Martin in 'Batang Quiapo,' another adaptation of a Fernando Poe Jr. project, as he praised Coco for…",
            "summary": "Sen. Lito Lapid (Facebook)\nSenator Lito Lapid announced his return to primetime television with Coco Martin in 'Batang Quiapo,' another adaptation of a Fernando Poe Jr. project, as he praised Coco for giving importance to fellow actors.\n'Minsan napagusapan namin sabi ko ayaw mo bang pumasok sa pulitika? Sabi niya, ‘ayoko po.' Hindi na ako namilit. Ayokong mangulit. Ayaw niya eh. Sabi niya aanhin ko naman ang pulitika kung kumikita naman ako? (Once we talked, I said do you not want to enter politics? He said, ‘I don't want to.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Robert Requintina",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/lapid1.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "d5acb91740f0a6ba66ba76c003dec19f"
        },
        {
            "title": "ADB OKs $500-M loan to aid PH agri sector, improve food security",
            "author": "Gma News",
            "published_date": "2023-01-27 02:39:35",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/money/economy/858801/adb-oks-500-m-loan-to-aid-ph-agri-sector-improve-food-security/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "The Asian Development Bank (ADB) has approved a $500-million policy-based loan to assist the Philippine government in expanding economic opportunities in the agriculture sector and ensuring food…",
            "summary": "Published January 27, 2023 10:39am The Asian Development Bank (ADB) has approved a $500-million policy-based loan to assist the Philippine government in expanding economic opportunities in the agriculture sector and ensuring food security for the population. \"Extreme climate events and economic shocks are exacerbating the struggles of the agriculture sector to raise their productivity,' ADB Principal Natural Resources and Agriculture Economist for Southeast Asia Takeshi Ueda said in a statement. \"This new loan aims to support the Philippines' efforts to attain food security by building a competitive and inclusive agriculture sector that is characterized by improved efficiency, enhanced diversity, strengthened climate resilience, and higher farm incomes,\" he added.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
            "media": "https://images.gmanews.tv/webpics/2020/04/adb1_2020_04_13_20_37_00.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "5fcbf210aba8c0624d977fe8e767ad35"
        },
        {
            "title": "Five persons, including a woman, fall in Cebu, Talisay drug busts",
            "author": "SUNSTAR",
            "published_date": "2023-01-27 02:34:37",
            "published_date_precision": "full",
            "link": "https://www.sunstar.com.ph/article/1951882/cebu/local-news/five-persons-including-a-woman-fall-in-drug-busts-in-cebu-city-and-talisay-city",
            "clean_url": "sunstar.com.ph",
            "excerpt": "AT least five drug personalities, including a woman, were arrested, while more than P1.7 million worth of illegal drugs were confiscated in separate buy-bust operations in the...",
            "summary": "CEBU CITY. In Tres de Abril extension, Barangay San Nicolas, Cebu City, operatives of the Regional Police Drug Enforcement Unit nabbed 2 suspects in possession of P714,000 worth of shabu. \n TALISAY CITY, CEBU. ​​​​​​​In Sitio Mananga 2, Barangay Tabunok, a certain Flordeliz Dacles, 40, was handcuffed by the operatives of Talisay City Drug Enforcement Unit led by Police Captain Lino Tryss Galvan around 10 p.m. AT least five drug personalities, including a woman, were arrested, while more than P1.7 million worth of illegal drugs were confiscated in separate buy-bust operations in the cities of Cebu and Talisay on Thursday evening, January 26, 2023.",
            "rights": "Copyright 2022,SUNSTAR",
            "rank": 16539,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "SUNSTAR",
            "media": "https://www.sunstar.com.ph/uploads/images/2023/01/27/410783.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "c0836dea655b0fe5104b9946e95087aa"
        },
        {
            "title": "Fire hits 2-storey house in Talisay City",
            "author": "SUNSTAR",
            "published_date": "2023-01-27 02:34:02",
            "published_date_precision": "full",
            "link": "https://www.sunstar.com.ph/article/1951881/cebu/local-news/fire-hits-2-storey-house-in-talisay-city",
            "clean_url": "sunstar.com.ph",
            "excerpt": "A two-storey house was razed by fire in Barangay Campo 4, Talisay City on Thursday evening, January 26, 2023.The house is allegedly owned by Gina...",
            "summary": "Photo courtesy of Talisay BFP A two-storey house was razed by fire in Barangay Campo 4, Talisay City on Thursday evening, January 26, 2023.The house is allegedly owned by Gina Arroga.Senior Fire Officer 4 Guiller Pegarido, deputy fire marshall of Talisay City Fire Station (TCFS), said the fire incident started at 8:36 p.m. and was declared fire out after 10 minutes.Pegarido pegged the damage at P75,000.The TCFS is now conducting an investigation to determine the cause of the fire. (BBT, TPT) Disclaimer SunStar website welcomes friendly debate, but comments posted on this site do not necessarily reflect the views of the SunStar management and its affiliates.",
            "rights": "Copyright 2022,SUNSTAR",
            "rank": 16539,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "SUNSTAR",
            "media": "https://www.sunstar.com.ph/uploads/images/2023/01/27/410785.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "c482d873f0344b248128c12688e900ce"
        },
        {
            "title": "Setting goals for 2023",
            "author": "MB Technews",
            "published_date": "2023-01-27 02:33:07",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/setting-goals-for-2023/",
            "clean_url": "mb.com.ph",
            "excerpt": "Written by Kim Lato I'm sure many of you are well into your new year's resolutions. What are you trying to improve this year? As a CEO, bringing out the best in people is one of the things I set out…",
            "summary": "Written by Kim Lato\n\nI'm sure many of you are well into your new year's resolutions. What are you trying to improve this year? As a CEO, bringing out the best in people is one of the things I set out to accomplish every day. I want people to find success. Everyone, however, defines success differently. It differs from person to person, generation to generation. \nWhen I ask people to define what success would be for them, the usual answers are economic comfort, professional fulfillment, and most common of them all: personal happiness and contentment.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": null,
            "authors": "MB Technews",
            "media": "https://lh4.googleusercontent.com/OdPz-5vauO8bC5_rTSTbw-cp6A2CEN94-8_InThMvZr_ioZ6kTe9etIl099a4azcQGz7SmyvguoC-AzORSS72uUtFzbmLOJFZtcDpiqWKpXbGZ3MLcGktEfHoaIIwGrF4CABYk9C8EufLVHUiXoITjYG-EdtIs6HsEH2h1Y2dKcRAZiLJbkpvtfVtW-f7A",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "9dd2550ca40f9db8e5bc665d0807b9b6"
        },
        {
            "title": "WATCH: Get a glimpse of J-Hope's artistry in teaser for Disney+ documentary",
            "author": "Gma News",
            "published_date": "2023-01-27 02:31:48",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/lifestyle/hobbiesandactivities/858800/get-a-glimpse-of-j-hope-s-artistry-in-teaser-for-disney-documentary/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "\"j-hope in the Box' will have its global premiere on Disney+ on February 17.",
            "summary": "WATCH Published January 27, 2023 10:31am 'People in the world don't know what kind of music J-Hope of BTS makes.\" This is what J-Hope said in the teaser trailer for 'j-hope in the Box,' but it looks like we'll be able to learn more about that soon! In the video, the South Korean rapper and dancer shared some snippets of him recording his first solo album 'Jack in the Box,' including dance rehearsals, the album launch party that BTS attended, and preparations for his headlining set at Lollapalooza 2022.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
            "media": "https://images.gmanews.tv/webpics/2023/01/jhop_lolla_2023_01_27_10_31_30.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "b8919fda2dca9593161365037dd8859d"
        },
        {
            "title": "Azurin: No courtesy resignation for PNP mid-level, junior officers, non-officers",
            "author": "Aaron Recuenco",
            "published_date": "2023-01-27 02:31:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/azurin-no-courtesy-resignation-for-pnp-mid-level-junior-officers-non-officers/",
            "clean_url": "mb.com.ph",
            "excerpt": "The courtesy resignation in the police force will only apply to third level officers, or from full colonel to generals, of the Philippine National Police (PNP). PNP chief Gen. Rodolfo Azurin, Jr.…",
            "summary": "The courtesy resignation in the police force will only apply to third level officers, or from full colonel to generals, of the Philippine National Police (PNP).\nPNP chief Gen. Rodolfo Azurin, Jr. explained that the process of assessment and evaluation by the Committee of Five, as well as its results, will serve as a strong message to all the police uniformed personnel that the organization is bent on purging the organization of those involved in illegal drugs trade.\n'There will be no courtesy resignation for middle ranking and junior officers and even our PNCOs (Police Non-Commissioned Officers).",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Aaron Recuenco",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122462.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "2ecd8ca9f407355b018ef38c924ffadc"
        },
        {
            "title": "Build your personal or business server with the Synology DS1522+",
            "author": "Jonathan Castillo",
            "published_date": "2023-01-27 02:30:41",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/build-your-personal-or-business-server-with-the-synology-ds1522/",
            "clean_url": "mb.com.ph",
            "excerpt": "For those building their businesses, you may want to check out the Synology DiskStation DS1522+, a powerful and reliable NAS device, which can be used for storage and file sharing. Of course, this isn't just for businesses, as it works very well for home users, allowing easier storing of photos and",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n \n\n\n\nFor those building their businesses, you may want to check out the Synology DiskStation DS1522+, a powerful and reliable NAS device, which can be used for storage and file sharing. Of course, this isn't just for businesses, as it works very well for home users, allowing easier storing of photos and other files for everyone to access.\nThe DS1522+ is equipped with an AMD Ryzen 1600 CPU, 8GB of RAM, and five hard drive bays, which can be expanded with ten additional bays.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Jonathan Castillo",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/Apple-Airport-Extreme.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "8ef5bf3c4b5cf2ed3cdd201f9f938b8d"
        },
        {
            "title": "Reported death toll from bad weather now at 40 — NDRRMC",
            "author": "Gma News",
            "published_date": "2023-01-27 02:24:52",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/topstories/nation/858799/reported-death-toll-from-bad-weather-reaches-40-ndrrmc/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "There are now 40 reported fatalities due to inclement weather felt in many areas in the country since January 1, the National Disaster Risk Reduction and Management Council (NDRRMC) said Friday.",
            "summary": "Published January 27, 2023 10:24am There are now 40 reported fatalities due to inclement weather felt in many areas in the country since January 1, the National Disaster Risk Reduction and Management Council (NDRRMC) said Friday. In its 6 a.m. report, the NDRRMC said 12 of the reported deaths were in Zamboanga, 10 in Bicol, eight in Northern Mindanao, seven in Eastern Visayas, and one each in Mimaropa, Davao and Soccsksargen. Only 20 of the reported fatalities have been confirmed so far, according to the NDRRMC.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
            "media": "https://images.gmanews.tv/webpics/2023/01/flood_2023_01_11_10_42_47.jpg",
            "is_opinion": false,
            "twitter_account": "@GMANewsOnline",
            "_score": null,
            "_id": "a849398a47e73d2ee25b2ea5b7509526"
        },
        {
            "title": "Quezon City mayor warns individuals spreading bomb threats",
            "author": "Arlie O. Calalo",
            "published_date": "2023-01-27 02:17:32",
            "published_date_precision": "full",
            "link": "https://www.manilatimes.net/2023/01/27/news/quezon-city-mayor-warns-individuals-spreading-bomb-threats/1876094",
            "clean_url": "manilatimes.net",
            "excerpt": "PIQUED by pranksters who spread bomb threats in schools, Quezon City Mayor Maria Josefina 'Joy' Belmonte warned on Friday that they will be dealt with accordingly when...",
            "summary": "PIQUED by pranksters who spread bomb threats in schools, Quezon City Mayor Maria Josefina \"Joy\" Belmonte warned on Friday that they will be dealt with accordingly when caught.Belmonte told The Manila Times that the incidents at the New Era Elementary School, San Jacinto High School, San Francisco High School and Ponciano Bernardo High School this week could no longer be taken lightly.The explosive ordnance disposal unit of the Quezon City Police District (QCPD) did not find any explosives in these schools.",
            "rights": "manilatimes.net",
            "rank": 7400,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Arlie O. Calalo",
            "media": "https://www.manilatimes.net/manilatimes/uploads/images/2023/01/27/152044.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "4431fa0de859fe3fb52c81add802d9c6"
        },
        {
            "title": "Rains persist over parts of Luzon, Visayas; Mindanao to have improved weather conditions",
            "author": "Ellalyn De Vera-Ruiz",
            "published_date": "2023-01-27 02:17:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/rains-persist-over-parts-of-luzon-visayas-mindanao-to-have-improved-weather-conditions/",
            "clean_url": "mb.com.ph",
            "excerpt": "(COURTESY OF MB VISUAL CONTENT GROUP)\n\r\rThe low pressure area east of Mindanao dissipated on Thursday, Jan. 26, but the shear line and northeast monsoon may continue to bring rains over parts of Luzon and Visayas this weekend, said the Philippine Atmospheric, Geophysical and Astronomical Services Ad",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n \n(COURTESY OF MB VISUAL CONTENT GROUP)\n The low pressure area east of Mindanao dissipated on Thursday, Jan. 26, but the shear line and northeast monsoon may continue to bring rains over parts of Luzon and Visayas this weekend, said the Philippine Atmospheric, Geophysical and Astronomical Services Administration (PAGASA) on Friday, Jan. 27.\nPAGASA said cloudy skies with scattered rain showers and thunderstorms because of the shear line may prevail over Eastern Visayas, Aklan, Capiz, Albay, Masbate, Sorsogon, Catanduanes, Palawan, and Romblon.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Ellalyn De Vera-Ruiz",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122456.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "1630e6edafe9c97332d279965b15f97f"
        },
        {
            "title": "Feast of Saint Thomas Aquinas on Jan. 28",
            "author": "Christina Hermoso",
            "published_date": "2023-01-27 02:17:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/feast-of-saint-thomas-aquinas-on-jan-28/",
            "clean_url": "mb.com.ph",
            "excerpt": "The Roman Catholic Church will observe on Saturday, Jan. 28, the Feast of Saint Thomas Aquinas (Santo Tomas de Aquino), one of the greatest and most influential Christian philosophers and theologians of all time.\n\r\r\n\nSt. Thomas Aquinas (Catholic Online)\n\r\rCommemorative masses will be offered at the",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\nThe Roman Catholic Church will observe on Saturday, Jan. 28, the Feast of Saint Thomas Aquinas (Santo Tomas de Aquino), one of the greatest and most influential Christian philosophers and theologians of all time. \nSt. Thomas Aquinas (Catholic Online)\n Commemorative masses will be offered at the St. Thomas Aquinas Parish in Mangaldan, Pangasinan as well as in Sto. Tomas, Batangas; Aliaga, Nueva Ecija; and in Abucay, Bataan.\nTriduum masses in honor of the popular saint will also be celebrated at the Sto.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Christina Hermoso",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122455.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "10c37f1d985cb431935052d3456c7106"
        },
        {
            "title": "Comment on Alex Eala loses to Swiss rival for second straight time by pisos a reformar centro",
            "author": "Tempo Desk",
            "published_date": "2023-01-27 02:11:47",
            "published_date_precision": "full",
            "link": "https://tempo.com.ph/2021/04/09/alex-eala-loses-to-swiss-rival-for-second-straight-time/#comment-62464",
            "clean_url": "tempo.com.ph",
            "excerpt": "ALEX EALA By JEREMIAH SEVILLA Swiss Simona Waltert is fast turning out to be the scourge of Alex Eala. Unable",
            "summary": "Good site you've got here.. It's hard to find quality writing like yours \nnowadays. I seriously appreciate individuals like \nyou! Take care!!",
            "rights": "tempo.com.ph",
            "rank": 171174,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Tempo Desk,http://tempo.com.ph",
            "media": "https://files.tempo.com.ph/wp-content/uploads/2021/03/alex-eala-fb7.jpg",
            "is_opinion": false,
            "twitter_account": "http://tempo.com.ph",
            "_score": null,
            "_id": "4317afa274d7288c6c96525b2f3ce9ad"
        },
        {
            "title": "Under a ‘culture of peace', MP NurRedha Misuari keeps flame of Bangsamoro dreams burning",
            "author": "Johaira Sahidala",
            "published_date": "2023-01-27 02:02:57",
            "published_date_precision": "full",
            "link": "https://www.mindanews.com/feature/2023/01/under-a-culture-of-peace-mp-nurredha-misuari-keeps-flame-of-bangsamoro-dreams-burning/",
            "clean_url": "mindanews.com",
            "excerpt": "Member of Parliament NurRedha Ibrahim Misuari. MindaNews photo by MANMAN DEJETO COTABATO CITY (MindaNews / 27 January) – NurRedha Ibrahim Misuari is no stranger to the Bangsamoro struggle. But unli…",
            "summary": "Member of Parliament NurRedha Ibrahim Misuari. MindaNews photo by MANMAN DEJETO COTABATO CITY (MindaNews / 27 January) – NurRedha Ibrahim Misuari is no stranger to the Bangsamoro struggle. But unlike her father Nur Misuari, founding chair of the Moro National Liberation Front (MNLF) who led a bloody armed revolution in the 1970s during the term of the late President Ferdinand Marcos, Sr., she is now waging a jihad (struggle) for the Bangsamoro people in Mindanao not in a war zone but in the battlefield that is the Bangsamoro Transition Authority (BTA).",
            "rights": "mindanews.com",
            "rank": 100461,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Johaira Sahidala",
            "media": "https://www.mindanews.com/wp-content/uploads/2022/09/03MisuariN33.jpg?w=640",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "1132acea96686a68a05c612b946e86fb"
        },
        {
            "title": "Akio Toyoda to become Toyota Chairman",
            "author": "Inigo Roces",
            "published_date": "2023-01-27 02:02:37",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/akio-toyoda-to-become-toyota-chairman/",
            "clean_url": "mb.com.ph",
            "excerpt": "Akio Toyoda, new Toyota Motor Corporation chairman of the board. (Photo by Noriaki Mitsuhashi, N-RAK Photo Agency) The man behind Gazoo Racing (GR Performance) and the return of such iconic models as…",
            "summary": "Akio Toyoda, new Toyota Motor Corporation chairman of the board. (Photo by Noriaki Mitsuhashi, N-RAK Photo Agency) The man behind Gazoo Racing (GR Performance) and the return of such iconic models as the FJ Cruiser, GR Supra, and GR Yaris will no longer be the president and CEO of Toyota Motor Corporation.\nAkio Toyoda has stepped down from his role as president and CEO but will ascend to be the Chairman of the Board of Directors of the company, effective April 1, 2023. Toyoda succeeds Takeshi Uchiyamada, who has stepped down as chairman but will remain a member of the board.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Inigo Roces",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/012723AkioToyoda1-1024x576.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "61680164713f0783323f8875d70ef3dd"
        },
        {
            "title": "Composting provides unexpected benefits to dairy farms in New Zealand",
            "author": "Manila Bulletin Agriculture",
            "published_date": "2023-01-27 02:00:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/composting-provides-unexpected-benefits-to-dairy-farms-in-new-zealand/",
            "clean_url": "mb.com.ph",
            "excerpt": "Research in New Zealand determined the feasibility of using composting shelters to house cows, a practice becoming popular among smallholder farmers.",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n \n\nDairy farms emit vast quantities of carbon dioxide and methane, making them one of the leading agricultural industries contributing to greenhouse gas emissions. Composting has long been known to help reduce emissions and turn organic waste into more beneficial products. \nPhoto: Balazs Simon/Pexels\n\nResearch in New Zealand determined the feasibility of using composting shelters to house cows, a practice becoming popular among smallholder farmers.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Manila Bulletin Agriculture",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/cow_16012023-2-1024x683.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "b73ae4b391e9b66c9b15b103c2c7e31f"
        },
        {
            "title": "PH Army chief of staff gets second star",
            "author": "Priam Nepomuceno",
            "published_date": "2023-01-27 02:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.pna.gov.ph/articles/1193715",
            "clean_url": "pna.gov.ph",
            "excerpt": "MANILA – Philippine Army (PA) Chief of Staff Maj. Gen. Potenciano C. Camba has received his second star rank.PA commander Lt. Gen. Romeo Brawner Jr. presided over the donning of ranks rites at the Army headquarters in Fort Bonifacio on Thursday.\"Maj. Gen. Potenciano C. Camba assumed as...",
            "summary": "Philippine Army (PA) Chief of Staff Maj. Gen. Potenciano C. Camba (Photo courtesy of Philippine Army)\n\nMANILA – Philippine Army (PA) Chief of Staff Maj. Gen. Potenciano C. Camba has received his second star rank.\n\nPA commander Lt. Gen. Romeo Brawner Jr. presided over the donning of ranks rites at the Army headquarters in Fort Bonifacio on Thursday.\n\n\"Maj. Gen. Potenciano C. Camba assumed as the Army chief of staff on Jan. 13, 2023, succeeding Maj. Gen. Jose Eriel M. Niembra who served as acting chief of staff on top of his primary duty as Army inspector general,\" PA spokesperson Col.",
            "rights": "pna.gov.ph",
            "rank": 15620,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Priam Nepomuceno",
            "media": "https://files01.pna.gov.ph/ograph/2023/01/27/ph-army-chief-of-staff-maj-gen-potenciano-cambaph-army-photo.jpg",
            "is_opinion": false,
            "twitter_account": "@pnagovph",
            "_score": null,
            "_id": "2e58db1f41a80adeb5835daff5fd4153"
        },
        {
            "title": "PBBM eyes ‘drastic' reforms to curb smuggling",
            "author": "Ruth Abbey Gita-Carlos",
            "published_date": "2023-01-27 01:57:00",
            "published_date_precision": "full",
            "link": "https://www.pna.gov.ph/articles/1193717",
            "clean_url": "pna.gov.ph",
            "excerpt": "MANILA – President Ferdinand R. Marcos Jr. is seeking 'drastic' reforms in the bureaucracy to address rampant smuggling, which he said 'threatens local industries and affects government tax collection.''(The President) is pushing for the digitalization of...",
            "summary": "DESTROYED. Some PHP395 million worth of smuggled cigarettes seized by the Bureau of Customs (BOC) and other agencies of government from May to November this year is destroyed Tuesday (Dec. 13, 2022) in Barangay Baliwasan, Zamboanga City. BOC-Zamboanga district collector Segundo Sigmundfreud Barte Jr. (2nd right) said the agency would continue its anti-smuggling campaign in this part of the country. (PNA photo by Teofilo P. Garcia Jr.)\n\nMANILA – President Ferdinand R. Marcos Jr. is seeking 'drastic' reforms in the bureaucracy to address rampant smuggling, which he said 'threatens local industries and affects government tax collection.",
            "rights": "pna.gov.ph",
            "rank": 15620,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Ruth Abbey Gita-Carlos",
            "media": "https://files01.pna.gov.ph/ograph/2022/12/13/boc-destroyed.png",
            "is_opinion": false,
            "twitter_account": "@pnagovph",
            "_score": null,
            "_id": "2b653d383fd5d7c49791d1c548abf736"
        },
        {
            "title": "Comment on Alex Eala loses to Swiss rival for second straight time by best crypto signals telegram",
            "author": "Tempo Desk",
            "published_date": "2023-01-27 01:56:44",
            "published_date_precision": "full",
            "link": "https://tempo.com.ph/2021/04/09/alex-eala-loses-to-swiss-rival-for-second-straight-time/#comment-62457",
            "clean_url": "tempo.com.ph",
            "excerpt": "ALEX EALA By JEREMIAH SEVILLA Swiss Simona Waltert is fast turning out to be the scourge of Alex Eala. Unable",
            "summary": "Does your site have a contact page? I'm having trouble \nlocating it but, I'd like to send you an e-mail. I've got some ideas \nfor your blog you might be interested in hearing. Either way, great website and I look forward to seeing \nit grow over time.",
            "rights": "tempo.com.ph",
            "rank": 171174,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Tempo Desk,http://tempo.com.ph",
            "media": "https://files.tempo.com.ph/wp-content/uploads/2021/03/alex-eala-fb7.jpg",
            "is_opinion": false,
            "twitter_account": "http://tempo.com.ph",
            "_score": null,
            "_id": "d0b9ad97ce6056b134f03e3bf6698fcc"
        },
        {
            "title": "80 more OFWs return home from Kuwait",
            "author": "Aric John Sy Cua",
            "published_date": "2023-01-27 01:55:24",
            "published_date_precision": "full",
            "link": "https://www.manilatimes.net/2023/01/27/news/80-more-ofws-return-home-from-kuwait/1876092",
            "clean_url": "manilatimes.net",
            "excerpt": "ANOTHER batch of Overseas Filipino Workers (OFWs) have gone home from Kuwait.The Overseas Workers Welfare Administration (OWWA) announced on Friday that 80 OFWs have returned to...",
            "summary": "ANOTHER batch of Overseas Filipino Workers (OFWs) have gone home from Kuwait.The Overseas Workers Welfare Administration (OWWA) announced on Friday that 80 OFWs have returned to the country at 5:40 a.m. on Friday at the Ninoy Aquino International Airport (NAIA) Terminal 3.The agency said this is the fourth batch of OFWs that came from Kuwait, following Administrator Arnell Ignacio's visit to the Middle Eastern country. These OFWs were also greeted by OWWA repatriation team director Luisa Reyes.A fifth batch will head home at the end of this month.",
            "rights": "manilatimes.net",
            "rank": 7400,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Aric John Sy Cua",
            "media": "https://www.manilatimes.net/manilatimes/uploads/images/2023/01/27/152042.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "36bde1a2294c0a86db3b441f8a52bbed"
        },
        {
            "title": "Dela Rosa wants reservists, higher military recruitment for mandatory ROTC",
            "author": "Hannah Torregoza",
            "published_date": "2023-01-27 01:54:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/dela-rosa-wants-reservists-higher-military-recruitment-for-mandatory-rotc/",
            "clean_url": "mb.com.ph",
            "excerpt": "Senator Ronald 'Bato' Dela Rosa on Friday, January 27 said he is considering tapping reservists to implement the proposed mandatory Reserve Officers Training Course (ROTC) in higher education…",
            "summary": "Senator Ronald 'Bato' Dela Rosa on Friday, January 27 said he is considering tapping reservists to implement the proposed mandatory Reserve Officers Training Course (ROTC) in higher education institutions (HEIs). Dela Rosa was earlier annoyed after a Department of National Defense (DND) official implied that the Armed Forces of the Philippines (AFP) may not be ready for the enormous task given that the military would need to tap 9,000 to 10,000 personnel for some 2,400 colleges and universities in the country.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Hannah Torregoza",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122453.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "ff94fe91843682eee41732fd862147e6"
        },
        {
            "title": "Blake Lively, Justin Baldoni to star in adaptation of Colleen Hoover's 'It Ends with Us'",
            "author": "Gma News",
            "published_date": "2023-01-27 01:42:51",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/lifestyle/hobbiesandactivities/858798/blake-lively-justin-baldoni-to-star-in-adaptation-of-colleen-hoover-s-it-ends-with-us/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Blake Lively and Justin Baldoni are set to star in the movie adaption of the Colleen Hoover novel 'It Ends with Us.'",
            "summary": "Published January 27, 2023 9:42am Photos: Blake Lively (IG) and Justin Baldoni (IG) Blake Lively and Justin Baldoni are set to star in the movie adaption of the Colleen Hoover novel 'It Ends with Us.' According to an exclusive report on Deadline, Justin will also direct the film, Blake and Colleen will be executive producers, and Christy Hall will adapt the script. This is Blake's first acting project in three years after 'The Rhythm Section' in 2020. The 'Gossip Girl' actress debuted as a director in 2021 for the Taylor Swift music video 'I Bet You Think About Me.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
            "media": "https://images.gmanews.tv/webpics/2023/01/composite(20)_2023_01_27_09_42_10.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "30aad4e12a957eb1c8d6a68ea0bf207a"
        },
        {
            "title": "Unang Balita sa Unang Hirit: JANUARY 27, 2023 [HD]",
            "author": "GMA News Online",
            "published_date": "2023-01-27 01:41:53",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/video/unangbalita/614187/unang-balita-sa-unang-hirit-january-27-2023-hd/video/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Narito ang mga nangungunang balita ngayong FRIDAY, JANUARY 27, 2023: -Pag-alis sa term limit ng elected officials, isinusulong sa panukalang chacha -EJ Obiena, nanalo ng silver medal sa…",
            "summary": "We use cookies to ensure you get the best browsing experience. By continued use, you agree to our privacy policy and accept our use of such cookies. For further information, click FIND OUT MORE.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "GMA News Online",
            "media": "https://i3.ytimg.com/vi/ZWKbbd6N4kE/0.jpg",
            "is_opinion": false,
            "twitter_account": "@GMANewsOnline",
            "_score": null,
            "_id": "8993aab64075b242458df8b77eb74066"
        },
        {
            "title": "Driving the all-new Honda BR-V to Baguio",
            "author": "Neil N. Pagulayan",
            "published_date": "2023-01-27 01:29:56",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/driving-the-all-new-honda-br-v-to-baguio/",
            "clean_url": "mb.com.ph",
            "excerpt": "Is a vehicle's ability to go up to a Baguio still a yardstick for its capabilities? Your Titos probably still ask that to determine the worthiness of any car. It's still a good and timely argument, as…",
            "summary": "Is a vehicle's ability to go up to a Baguio still a yardstick for its capabilities? Your Titos probably still ask that to determine the worthiness of any car. It's still a good and timely argument, as last week, our friends from Honda invited us to take the recently launched all-new Honda BR-V for a quick road trip up to Baguio.\n\nWith three or four of us in each vehicle and a long drive ahead, we were all guaranteed time behind the wheel to experience Honda's latest offering. We drove the top spec VX variant.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Neil N. Pagulayan",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/012723HondaBRV1-1024x576.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "bf2aa694ca4e0f7872e9d9da74a1ff66"
        },
        {
            "title": "Presyo ng bulaklak nagsimula ng sumirit",
            "author": "",
            "published_date": "2023-01-27 01:29:22",
            "published_date_precision": "full",
            "link": "https://tnt.abante.com.ph/2023/01/27/presyo-ng-bulaklak-nagsimula-ng-sumirit/news",
            "clean_url": "abante.com.ph",
            "excerpt": null,
            "summary": "At dahil papalapit na ang buwan ng Pebrero, nagsisimula na rin na tumaas ang presyo ng bulaklak.\nThe post Presyo ng bulaklak nagsimula ng sumirit first appeared on Abante TNT.",
            "rights": null,
            "rank": 221300,
            "topic": "news",
            "country": "PH",
            "language": "tl",
            "authors": "",
            "media": null,
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "57cecea24f328e1385c286e6be27711c"
        },
        {
            "title": "Inangkat na galunggong dumating na sa ‘Pinas",
            "author": "",
            "published_date": "2023-01-27 01:28:36",
            "published_date_precision": "full",
            "link": "https://tnt.abante.com.ph/2023/01/27/inangkat-na-galunggong-dumating-na-sa-pinas/news",
            "clean_url": "abante.com.ph",
            "excerpt": null,
            "summary": "Dahil sa closed fishing season ng galunggong, nakuhang mag-import ng bansa ng galunggong.\nThe post Inangkat na galunggong dumating na sa ‘Pinas first appeared on Abante TNT.",
            "rights": null,
            "rank": 221300,
            "topic": "news",
            "country": "PH",
            "language": "tl",
            "authors": "",
            "media": null,
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "046af142a745488575fa046a02253a05"
        },
        {
            "title": "UK aims to be one of PH's top investors",
            "author": "Joseph Pedrajas",
            "published_date": "2023-01-27 01:24:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/uk-aims-to-be-one-of-phs-top-investors/",
            "clean_url": "mb.com.ph",
            "excerpt": "The United Kingdom is wishing to become one of the Philippines​' top investors considering the country's wide market and the government's measures to ensure easier access to conducting business…",
            "summary": "The United Kingdom is wishing to become one of the Philippines​' top investors considering the country's wide market and the government's measures to ensure easier access to conducting business transactions.\nUK Ambassador to the Philippine Laure Beaufils said UK ​'​wants to capitalize​'​ on the country's unsaturated and English-speaking market as well as ​on its 'big demographic dividend' and the people's 'strong, ethical workforce.'​​\n​'​We want to be among your top investors… We want more British investment.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Joseph Pedrajas",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122450.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "daa0d27bc5bba679c03771415060932c"
        },
        {
            "title": "Snap better photos with the Xiaomi 12T Pro",
            "author": "MB Technews",
            "published_date": "2023-01-27 01:22:37",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/snap-better-photos-with-the-xiaomi-12t-pro/",
            "clean_url": "mb.com.ph",
            "excerpt": "Elevate your smartphone photography game with the Xiaomi 12T Pro, an advanced triple-camera setup with high-resolution capabilities. Whether you're a professional photographer, or just looking to up…",
            "summary": "Elevate your smartphone photography game with the Xiaomi 12T Pro, an advanced triple-camera setup with high-resolution capabilities. Whether you're a professional photographer, or just looking to up your Instagram game, the Xiaomi 12T Pro offers a range of features to take your photos to the next level.\nThe Xiaomi 12T Pro allows you to easily capture stunning images. But it's not just about the camera's technical capabilities that matter, it's also about knowing how to use them.\nExperiment with different shooting modes\nThe Xiaomi 12T Pro's main camera boasts a resolution of 200 megapixels, more than enough to capture stunning images on the fly.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "MB Technews",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/12T-Series-Master-Class-1024x576.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "6c411e431f09e01bbde1171eb002277e"
        },
        {
            "title": "‘Ano kaya meron?': Sen. Bato questions ICC's motive in insisting probe on PH's drug war",
            "author": "Hannah Torregoza",
            "published_date": "2023-01-27 01:21:00",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/ano-kaya-meron-sen-bato-questions-iccs-motive-in-insisting-probe-on-phs-drug-war/",
            "clean_url": "mb.com.ph",
            "excerpt": "Senator Ronald 'Bato' Dela Rosa on Friday, January 27 expressed his belief there are some people who are indeed pushing for the International Criminal Court (ICC) to pursue an investigation into the…",
            "summary": "Senator Ronald 'Bato' Dela Rosa on Friday, January 27 expressed his belief there are some people who are indeed pushing for the International Criminal Court (ICC) to pursue an investigation into the Philippines' war on drugs during the administration of President Rodrigo Duterte. Dela Rosa floated the idea when asked to weigh in on the ICC's latest decision to resume its investigation into the controversial war on drugs launched by then President Rodrigo Duterte. A former Philippine National Police (PNP) chief, Dela Rosa headed the so-called 'Oplan Tokhang' that led to the deaths of thousands of drug suspects in the Philippines during the Duterte administration.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Hannah Torregoza",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/122451.jpeg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "880ec055fb58ae315cb7467997c87a56"
        },
        {
            "title": "Apple, please bring back the AirPort Extreme",
            "author": "Professor Rom Feria",
            "published_date": "2023-01-27 01:20:59",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/apple-please-bring-back-the-airport-extreme/",
            "clean_url": "mb.com.ph",
            "excerpt": "The resurrection of the HomePod gives us hope that Apple can do the same for other products that they killed off. In this age of privacy invasion by most companies and Apple being in the forefront of…",
            "summary": "The resurrection of the HomePod gives us hope that Apple can do the same for other products that they killed off. In this age of privacy invasion by most companies and Apple being in the forefront of the fight to protect user privacy, the next frontier to protect is the home network. \nApple has built-in protection on its devices and the cloud, with Advance Data Protection, it is time to protect the data coming in and going out of the home network. The home network is not foreign to Apple as it had the Airport line before.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Professor Rom Feria",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/Apple-Airport-Extreme.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "16afe89faf16d8e991e860258fbd9dd3"
        },
        {
            "title": "Bato dela Rosa eyes tapping reservists, higher military recruitment quota for mandatory ROTC",
            "author": "Gma News",
            "published_date": "2023-01-27 01:20:34",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/topstories/nation/858797/bato-dela-rosa-eyes-tapping-reservists-higher-military-recruitment-quota-for-mandatory-rotc/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Senator Ronald 'Bato' dela Rosa on Friday said he is considering tapping reservists and increasing the quota on the military recruitment to have the manpower needed to implement the proposed mandatory…",
            "summary": "Published January 27, 2023 9:20am Senator Ronald 'Bato' dela Rosa on Friday said he is considering tapping reservists and increasing the quota on the military recruitment to have the manpower needed to implement the proposed mandatory Reserve Officers Training Course (ROTC) in higher education institutions. Interviewed on GMA News' Unang Balita, Dela Rosa was asked for his solution regarding the concern expressed by Defense Undersecretary Franco Gacal that the program would need 9,000 to 10,000 military personnel.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
            "media": "https://images.gmanews.tv/webpics/2022/07/buscalan_2022_07_25_18_54_57.jpg",
            "is_opinion": false,
            "twitter_account": "@GMANewsOnline",
            "_score": null,
            "_id": "a7c5433a33c3bad58217f3f429651863"
        },
        {
            "title": "Mitsubishi unveils the new Xpander Cross",
            "author": "Inigo Roces",
            "published_date": "2023-01-27 01:19:06",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/mitsubishi-unveils-the-new-xpander-cross/",
            "clean_url": "mb.com.ph",
            "excerpt": "Shortly after the unveiling of the new Xpander, Mitsubishi brings those same improvements to its much more rugged stablemate, the Xpander Cross. Designed to be a fusion of MPV and SUV functionality…",
            "summary": "Shortly after the unveiling of the new Xpander, Mitsubishi brings those same improvements to its much more rugged stablemate, the Xpander Cross.\nDesigned to be a fusion of MPV and SUV functionality and capability, the Xpander Cross offers more SUV-like design and characteristics with the same versatility as the MPV it is based on.\nModern design\n\nLike the refreshed Xpander, the 2023 Xpander Cross bears the unique T-shaped LED headlights with daytime running lights (DRL) and LED fog lamps. It also carries over onto the rear taillights.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Inigo Roces",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/012723MitsuXpanderCross9-1024x576.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "048d406a1a18552d578b090d85fb2cac"
        },
        {
            "title": "Janine Gutierrez humanga sa talento ni Dolly de Leon",
            "author": "",
            "published_date": "2023-01-27 01:16:39",
            "published_date_precision": "full",
            "link": "https://tnt.abante.com.ph/2023/01/27/janine-gutierrez-humanga-sa-talento-ni-dolly-de-leon/showbiz",
            "clean_url": "abante.com.ph",
            "excerpt": null,
            "summary": "Naging fan girl ang aktres na si Janine Gutierrez matapos makatrabaho si Dolly de Leon.\nThe post Janine Gutierrez humanga sa talento ni Dolly de Leon first appeared on Abante TNT.",
            "rights": null,
            "rank": 221300,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "",
            "media": null,
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "6bd3106e7508e816b44a991c4af02b39"
        },
        {
            "title": "Cherry introduces new accessories to liven up the lifestyte",
            "author": "MB Technews",
            "published_date": "2023-01-27 01:14:20",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/cherry-introduces-new-accessories-to-liven-up-the-lifestyte/",
            "clean_url": "mb.com.ph",
            "excerpt": "Cherry beats the challenge to keep current as it constantly expands technological innovations improving quality and ease of life. Choose the device that best suits your lifestyle as we get to know more about Cherry Accessories Must-have: Cherry Home Smart Universal Extension Cord, Cherry Cube and Ca",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n \n \nCherry beats the challenge to keep current as it constantly expands technological innovations improving quality and ease of life. Choose the device that best suits your lifestyle as we get to know more about Cherry Accessories Must-have: Cherry Home Smart Universal Extension Cord, Cherry Cube and Capsule Earbuds, Cherry Smart Watch. \n\nCherry Home Smart Universal Extension Cord: If energy conservation is your top priority. \nAs we use different gadgets to spice up our daily life, we also need built-in safety features to keep them secured.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "MB Technews",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/Apple-Airport-Extreme.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "215ec2f84a9a7cd509ae7b7317861507"
        },
        {
            "title": "ASUS celebrates 2.2 'No.1 OLED Festival' with up to 10% OFF on Vivobook and Zenbook devices",
            "author": "Jonathan Castillo",
            "published_date": "2023-01-27 01:11:54",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/asus-celebrates-2-2-no-1-oled-festival-with-up-to-10-off-on-vivobook-and-zenbook-devices/",
            "clean_url": "mb.com.ph",
            "excerpt": "Kickstart your year and enjoy big discounts this upcoming 2.2 no. 1 OLED Festival sale from the leading laptop brand in the Philippines, ASUS. Enjoy free shipping nationwide and get a chance to win a…",
            "summary": "Kickstart your year and enjoy big discounts this upcoming 2.2 no. 1 OLED Festival sale from the leading laptop brand in the Philippines, ASUS. Enjoy free shipping nationwide and get a chance to win a Vivobook laptop when you purchase any ASUS OLED laptops through the ASUS Official Store on Shopee and Lazada from January 28 to February 5, 2023 only. The lucky winner will be announced on February 10 through the official Facebook page of ASUS Philippines. \nAmazing true-to-life ASUS OLED colors\nOLED technology is now available across ASUS' Vivobook and Zenbook series.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Jonathan Castillo",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/Vivobook-S-Flip-OLED_2-1024x538.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "1986f45144394437be3e9af5c6ac2948"
        },
        {
            "title": "Kutis porselana! Sue Ramirez ‘nakakasilaw' ang balat",
            "author": "",
            "published_date": "2023-01-27 01:11:19",
            "published_date_precision": "full",
            "link": "https://tnt.abante.com.ph/2023/01/27/kutis-porselana-sue-ramirez-nakakasilaw-ang-balat/showbiz",
            "clean_url": "abante.com.ph",
            "excerpt": null,
            "summary": "Tila may ‘pasilip' din ito sa kaniyang ‘melon' dahil ang suot nito ay may hati sa gitna.\nThe post Kutis porselana! Sue Ramirez ‘nakakasilaw' ang balat first appeared on Abante TNT.",
            "rights": null,
            "rank": 221300,
            "topic": "news",
            "country": "PH",
            "language": "tl",
            "authors": "",
            "media": null,
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "1cd22e4d1ee8b2a881d588f11ab6d9ab"
        },
        {
            "title": "Peugeot PH records 285% growth in 2022",
            "author": "Eric R. Tipan",
            "published_date": "2023-01-27 01:09:03",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/peugeot-ph-records-285-growth-in-2022/",
            "clean_url": "mb.com.ph",
            "excerpt": "If you are seeing more Peugeots running around the metro, credit its new distributor Astara Philippines for significantly increasing its market share despite having only four nameplates locally, the…",
            "summary": "If you are seeing more Peugeots running around the metro, credit its new distributor Astara Philippines for significantly increasing its market share despite having only four nameplates locally, the 2008 SUV, the 3008 SUV, the 5008 SUV, and the Traveller Premium.\nPeugeot PH recorded a 285 percent rise in sales since the brand's relaunch in January 2022 and closed last year with 13 operation showrooms and service centers across the country. Six are in Metro Manila – Alabang, Balintawak, Makati, Manila Bay, Pasig, Quezon City; four in Luzon – Bulacan, Pampanga, Santa Rosa, Batangas; two in Visayas – Cebu, and Bacolod; and one in Mindanao – Davao.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Eric R. Tipan",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/012723Peugeot1.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "57cf931643e93d36788e76b43f5bd31c"
        },
        {
            "title": "Zack Tabudlo launches new era with 'Akin Ka'",
            "author": "Manila Bulletin Entertainment",
            "published_date": "2023-01-27 01:08:50",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/zack-tabudlo-launches-new-era-with-akin-ka/",
            "clean_url": "mb.com.ph",
            "excerpt": "After being hailed as Spotify's Top Streaming Domestic Artist for 2022, Zack Tabudlo breaks barriers again with 'AKIN KA,' a new record exploring a different side of his craft. Here, he explores with reckless abandon—it's unapologetic and passionate but remains a homage to the smooth soul musical ge",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\nCelebrities, Entertainment, Entertainment News, Music \n\n\n\n\nAfter being hailed as Spotify's Top Streaming Domestic Artist for 2022, Zack Tabudlo breaks barriers again with 'AKIN KA,' a new record exploring a different side of his craft. Here, he explores with reckless abandon—it's unapologetic and passionate but remains a homage to the smooth soul musical genre.\nZack sees the single as a mirror of his fun side since he took inspiration from funk and RnB classics, including legends like James Brown and Motown.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Manila Bulletin Entertainment",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/image006.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "7edc2405c2e1df4543bf5a313cb5584e"
        },
        {
            "title": "Google Philippines' Bernadette Nacario receives outstanding leadership award",
            "author": "MB Technews",
            "published_date": "2023-01-27 01:08:31",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/google-philippines-bernadette-nacario-receives-outstanding-leadership-award/",
            "clean_url": "mb.com.ph",
            "excerpt": "Google Philippines' Country Director Bernadette Nacario was recently recognized by the Women's Institute for Sustainable Development, Opportunities and Mentoring (WISDOM) and the American Chamber of…",
            "summary": "Google Philippines' Country Director Bernadette Nacario was recently recognized by the Women's Institute for Sustainable Development, Opportunities and Mentoring (WISDOM) and the American Chamber of Commerce of the Philippines  (AmCham Philippines) as one of the country's most outstanding women corporate leaders.\n\n\nWISDOM and AmCham Philippines awarded Nacario, along with other select women leaders, to acknowledge her contributions in weaving wonders in the Philippines' corporate landscape.\nIn 2022, Google continued to launch high-impact programs to help Filipinos reap the benefits of the country's growing digital economy.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "MB Technews",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/image003-4.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "f88e898d2eb9b86f3af315e358f91db2"
        },
        {
            "title": "PayMongo appoints Jojo Malolos as new CEO",
            "author": "Robert D. Reyes",
            "published_date": "2023-01-27 01:06:08",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/paymongo-appoints-jojo-malolos-as-new-ceo/",
            "clean_url": "mb.com.ph",
            "excerpt": "Digital payment company PayMongo has announced the appointment of Jojo Malolos as its new President and CEO. The appointment will take effect on February 1, 2023, and will see Isabel Ridad stepping down from her role as Interim CEO. Ridad will assist Malolos during the transition period and will con",
            "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\n\n\nDigital payment company PayMongo has announced the appointment of Jojo Malolos as its new President and CEO. The appointment will take effect on February 1, 2023, and will see Isabel Ridad stepping down from her role as Interim CEO. Ridad will assist Malolos during the transition period and will continue to serve on the PayMongo Board of Directors.\nAs the new CEO, Malolos will be responsible for leading PayMongo's efforts to enter the next phase of growth.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Robert D. Reyes",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/Apple-Airport-Extreme.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "7dde3243c93c2acbdda3d7283896ef2e"
        },
        {
            "title": "GCash, Grab Philippines join forces for more convenient direct cashless payment option",
            "author": "Jonathan Castillo",
            "published_date": "2023-01-27 01:03:01",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/gcash-grab-philippines-join-forces-for-more-convenient-direct-cashless-payment-option/",
            "clean_url": "mb.com.ph",
            "excerpt": "GCash and Grab mark their milestone partnership with GCash available as a direct payment option in the Grab app by February.(From left) GCash Chief Marketing Officer Neil Trinidad, GCash Head of…",
            "summary": "GCash and Grab mark their milestone partnership with GCash available as a direct payment option in the Grab app by February.(From left) GCash Chief Marketing Officer Neil Trinidad, GCash Head of Commercial Sales and Operations Luigi Reyes, GCash Chief Commercial Officer Ren-Ren Reyes, GrabFin Philippines President Martha Elaine Borja, Head of GrabPay Philippines Cris Alcaraz, and Grab Philippines Country Marketing Head Justine Anne Aruta\nPaying for your ride and food orders will soon be easier and hassle-free as the country's leading mobile wallet GCash partners with Grab Philippines, the country's leader in transportation and deliveries.",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Jonathan Castillo",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/GCash-and-Grab-partner-for-more-convenient-direct-payment-option-1024x668.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "0e3743d699aa471e1a201aaeb9b4770a"
        },
        {
            "title": "Kapuso sa Batas- Usapang kabit 101",
            "author": "GMA News Online",
            "published_date": "2023-01-27 01:02:22",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/video/unanghirit/614186/kapuso-sa-batas-usapang-kabit-101-unang-hirit/video/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Aired (January 27, 2023): USAPANG KABIT! Viral ang video kung saan nahuli sa akto ng asawa ang kanyang misis kasama ang isang pulis sa loob ng motel. May kaibahan ba sa puwedeng ikaso sakaling opisyal…",
            "summary": "We use cookies to ensure you get the best browsing experience. By continued use, you agree to our privacy policy and accept our use of such cookies. For further information, click FIND OUT MORE.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "GMA News Online",
            "media": "https://i3.ytimg.com/vi/-3oQpmrgyrM/0.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "8aa8a85c5caece3f8b99b619c15a09d3"
        },
        {
            "title": "‘Susunod na lang' dance challenge with UH Barkada",
            "author": "GMA News Online",
            "published_date": "2023-01-27 01:01:31",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/video/unanghirit/614185/susunod-na-lang-dance-challenge-with-uh-barkada-unang-hirit/video/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Aired (January 27, 2023): Sa susunod na lang… Na-LSS na rin ba kayo sa TikTok dance craze na ito? Aba, hindi magpapahuli ang UH Barkada kaya naman LIVE nating pinag-perform sa UH stage ang original…",
            "summary": "We use cookies to ensure you get the best browsing experience. By continued use, you agree to our privacy policy and accept our use of such cookies. For further information, click FIND OUT MORE.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "af",
            "authors": "GMA News Online",
            "media": "https://i3.ytimg.com/vi/FIMMw8gAcTg/0.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "fca1749f3657d6efa3795c2e117f5ea2"
        },
        {
            "title": "'NAKAKASAWA NA': Bato questions ICC's insistence to probe Philippine drug war",
            "author": "Joviland Rita",
            "published_date": "2023-01-27 01:00:32",
            "published_date_precision": "full",
            "link": "https://www.gmanetwork.com/news/topstories/nation/858796/dela-rosa-questions-icc-s-insistence-to-probe-philippine-drug-war/story/",
            "clean_url": "gmanetwork.com",
            "excerpt": "Senator Ronald 'Bato' dela Rosa on Friday questioned the motive of the International Criminal Court (ICC) in pushing through with its investigation into the Philippines' anti-drug war.",
            "summary": "'NAKAKASAWA NA' By JOVILAND RITA, GMA Integrated News Published January 27, 2023 9:00am Updated January 27, 2023 9:51am Senator Ronald 'Bato' dela Rosa on Friday questioned the motive of the International Criminal Court (ICC) in pushing through with its investigation into the Philippines' anti-drug war. Interviewed on GMA News' Unang Balita, Dela Rosa, the national police chief during the height of the drug war under the Duterte administration, said there seems to be an \"agenda\" behind the continuous push for the investigation.",
            "rights": " Copyright 2023 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
            "rank": 5469,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "GMA Integrated News,If Storyparsed.Issaf,JOVILAND RITA",
            "media": "https://images.gmanews.tv/webpics/2022/12/bato_dela_rosa_121222_2022_12_12_21_28_56.jpg",
            "is_opinion": false,
            "twitter_account": "@gmanews",
            "_score": null,
            "_id": "38e7ed5fe355cef95550fe410e5051b5"
        },
        {
            "title": "The Cast of \"Island,\" Cha Eun Woo's Trending K-Drama, and Where You've Seen Them Before",
            "author": "",
            "published_date": "2023-01-27 01:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.preview.ph/culture/island-korean-drama-cast-cha-eun-woo-a00378-20230127",
            "clean_url": "preview.ph",
            "excerpt": "The most comprehensive source for fashion, beauty, parties and celebrity style in the Philippines.",
            "summary": "The Prime Video K-drama has a part 2 coming soon!",
            "rights": "preview.ph",
            "rank": 121833,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "",
            "media": "https://www.preview.ph/preview-favicon.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "ade8792bbeb2ab5f275ffdb20b22554a"
        },
        {
            "title": "beep launches new Advance Booking System for Manila to Davao route",
            "author": "Jonathan Castillo",
            "published_date": "2023-01-27 00:58:44",
            "published_date_precision": "full",
            "link": "https://mb.com.ph/2023/01/27/beep-launches-new-advance-booking-system-for-manila-to-davao-route/",
            "clean_url": "mb.com.ph",
            "excerpt": "beep operator AF Payments Inc. is introducing its newest solution designed to make it more convenient for passengers to purchase their bus tickets. This is the Advance Booking System, which will first…",
            "summary": "beep operator AF Payments Inc. is introducing its newest solution designed to make it more convenient for passengers to purchase their bus tickets. This is the Advance Booking System, which will first be implemented by Davao Metro Shuttle (DMS) in its Metro Manila↔Davao route, the longest bus route to date.\nStarting January 27, commuters and even tourists will enjoy the convenience of reserving bus tickets in advance to lessen the hassle of queueing onsite. Passengers can purchase and rebook tickets ahead at the Parañaque Integrated Terminal Exchange (PITX) Terminal using their beep™ card or thru their advance booking hotline: Davao-PITX (0939-1351349) or PITX-Davao (0981-3313389).",
            "rights": "mb.com.ph",
            "rank": 5693,
            "topic": "news",
            "country": "PH",
            "language": "en",
            "authors": "Jonathan Castillo",
            "media": "https://mb.com.ph/wp-content/uploads/2023/01/beep-card2-1024x1024.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "64616a0bb29181606cf219fce488f6fe"
        }
    ],
    "user_input": {
        "lang": null,
        "not_lang": null,
        "countries": [
            "PH"
        ],
        "not_countries": null,
        "page": 1,
        "size": 50,
        "sources": null,
        "not_sources": null,
        "topic": "news",
        "from": "2023-01-13 03:40:04"
    }
}


export const Copyrights = [
    "inquirer.net",
    "mb.com.ph",
    "newsbreak.com",
    "manilatimes.net",
    "gmanetwork.com",
    "abs-cbn.com",
    "pna.gov.ph",
    "sunstar.com.ph",
    // // "businessmirror.com.ph",
    // "rappler.com",
    // "bworldonline.com",
    // "philnews.ph",
    // "malaya.com.ph",
    // "philstar.com",
    // "spin.ph",
    // // "thefinancialdistrict.com.ph",
    // "newspapers.ph",
    // "pageone.ph",
    // "senate.gov.ph",
    // "lionheartv.net",
    // "philippinetimes.com",
    // "punto.com.ph",
    // "villagepipol.com",
    // "manilametro.com",
    // "orangemagazine.ph",
    // "adobomagazine.com",
    // "visayandailystar.com",
    // "palawan-news.com",
    // "abante.com.ph",
    // "esquiremag.ph",
    // "licas.news",
    // "starmometer.com",
    // "tiebreakertimes.com.ph",
    // "manilashaker.com",
    // "tempo.com.ph",
    // "wheninmanila.com",
    // "candymag.com",
    // "manilarepublic.com",
    // "mims.com",
    // "topgear.com.ph",
    // "cnnphilippines.com",
    // "eaglenews.ph",
    // "noypigeeks.com",
    // "theglobalfilipinomagazine.com",
    // "wethepvblic.com",
    // "worldweeklynews.com",
    // "2ndopinion.ph",
    // "8list.ph",
    // "autodeal.com.ph",
    // "carguide.ph",
    // "latestchika.com",
    // "newsbytes.ph",
    // "philkotse.com",
    // "preview.ph",
    // "spot.ph",
    // "canberranews.net",
    // "technobaboy.com",
    // "autocar.com.ph",
    // "gadgetpilipinas.net",
    // "gadgetsmagazine.com.ph",
    // "goodnewspilipinas.com",
    // "journal.com.ph",
    // "mindanews.com",
    // "singaporestar.com",
    // "sugbo.ph",
    // "thedailyguardian.net",
    // "yehey.com",
    // "aseanmp.org",
    // "boholchronicle.com.ph",
    // "bomboradyo.com",
    // "cakafete.com",
    // "cbcpnews.net",
    // "cmfr-phil.org",
    // "gamingph.com",
    // "nolisoli.ph",
    // "outoftownblog.com",
    // "pba.ph",
    // "pep.ph",
    // "pinoymetrogeek.com",
    // "revu.com.ph",
    // "rmn.ph",
    // "shangbao.com.ph",
    // "smartparenting.com.ph",
    // "techpinas.com",
    // "theappwhisperer.com",
    // "thesummitexpress.com",
    // "ungeek.ph"
]