export const dataPublish = [
  {
    id: 1111,
    headline: "Lorem ipsum dolor sit ametLorem ipsum dolor sit amet consectetur adipisicing elit. A architecto cupiditate eius facere! Assumenda ",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. A architecto cupiditate eius facere! Assumenda illum laboriosam illo tempore consectetur in corrupti qui eveniet dolores et dolorem ipsa est porro voluptatibus dignissimos, quas accusamus mollitia fugiat vel beatae, natus expedita! Exercitationem, quibusdam! Asperiores nulla, alias optio sunt fuga et quis voluptas at hic eaque assumenda accusantium delectus odit ad placeat repellendus perferendis necessitatibus commodi vel doloremque suscipit dicta ab modi cum. Qui ipsam, molestiae ad praesentium ut odit porro perferendis quo quaerat ab doloribus nostrum vel? Reprehenderit nihil distinctio minus, repellendus quis ipsa delectus rerum consectetur possimus voluptatibus, esse numquam, libero ipsum molestias consequuntur exercitationem voluptatem amet explicabo nam. Quibusdam consequatur quam mollitia eos fugit, beatae fugiat deserunt, iste eveniet laudantium laboriosam, ea vitae repudiandae atque? Tempora suscipit, sunt quis laboriosam, aspernatur rerum quos odio magni nam quaerat commodi autem! Officiis, animi dolores doloribus libero voluptas accusamus optio soluta maxime velit.Lorem ipsum dolor sit amet consectetur adipisicing elit. A architecto cupiditate eius facere! Assumenda illum laboriosam illo tempore consectetur in corrupti qui eveniet dolores et dolorem ipsa est porro voluptatibus dignissimos, quas accusamus mollitia fugiat vel beatae, natus expedita! Exercitationem, quibusdam! Asperiores nulla, alias optio sunt fuga et quis voluptas at hic eaque assumenda accusantium delectus odit ad placeat repellendus perferendis necessitatibus commodi vel doloremque suscipit dicta ab modi cum. Qui ipsam, molestiae ad praesentium ut odit porro perferendis quo quaerat ab doloribus nostrum vel? Reprehenderit nihil distinctio minus, repellendus quis ipsa delectus rerum consectetur possimus voluptatibus, esse numquam, libero ipsum molestias consequuntur exercitationem voluptatem amet explicabo nam. Quibusdam consequatur quam mollitia eos fugit, beatae fugiat deserunt, iste eveniet laudantium laboriosam, ea vitae repudiandae atque? Tempora suscipit, sunt quis laboriosam, aspernatur rerum quos odio magni nam quaerat commodi autem! Officiis, animi dolores doloribus libero voluptas accusamus optio soluta maxime velit.",
    sentiment: "negative",
    sentimentrate: -100,
    plagiarizerate: 30.1,
    categories: "Sports",
    date: "Aug 8 2022 Tue",
    status: "For Review",
    remarks: "testing",
    action: "review",
    author: "Lorem Ipsum",
    oversentiment: false,
    source: "main",
    image:
      "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
  },
  {
    id: 1112,
    headline: "Lorem ipsum dolor sit Lorem ipsum dolor sit amet consectetur adipisicing elit. A architecto cupiditate eius facere! Assumenda ",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sagittis neque vel tristique tempor. Etiam interdum mi urna, et finibus ligula semper in. Ut a diam a sem volutpat gravida. Cras orci dolor, iaculis sit amet tortor at, fringilla dapibus quam. Duis consectetur magna a metus commodo vestibulum. Phasellus non ligula velit. Praesent a velit orci. Phasellus non commodo odio. Phasellus vitae velit neque. Nunc sollicitudin dui ante, id dapibus nulla venenatis sed. Suspendisse potenti. Nulla tincidunt metus eget elit commodo venenatis.  Suspendisse porttitor facilisis leo ac maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In vitae odio hendrerit quam pharetra euismod. Etiam accumsan lectus eget diam finibus cursus. Nam quis interdum sem. Duis ac consectetur tellus. Suspendisse tempor vitae tortor eget fringilla.Quisque ipsum lorem, fringilla a mollis nec, auctor quis magna. Mauris tincidunt tellus lacus, in interdum justo scelerisque id. Integer vitae efficitur diam. Curabitur venenatis auctor pretium. Suspendisse mattis sed nibh euismod pellentesque. Maecenas vulputate pellentesque nunc in varius. Maecenas nec felis cursus, maximus dui a, sagittis mauris. Morbi consequat dignissim erat, ultrices gravida lectus.",
    sentiment: "positive",
    sentimentrate: -100,
    plagiarizerate: 30.1,
    categories: "Tech",
    date: "Aug 8 2022 Tue",
    status: "For Review",
    remarks: "testing",
    action: "approved",
    author: "Lorem name",
    empId: "20188115635",
    oversentiment: false,
    source: "sources",
    image:
      "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
  },
  {
    id: 1113,
    headline: "Lorem ipsum dolor sit amet",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sagittis neque vel tristique tempor. Etiam interdum mi urna, et finibus ligula semper in. Ut a diam a sem volutpat gravida. Cras orci dolor, iaculis sit amet tortor at, fringilla dapibus quam. Duis consectetur magna a metus commodo vestibulum. Phasellus non ligula velit. Praesent a velit orci. Phasellus non commodo odio. Phasellus vitae velit neque. Nunc sollicitudin dui ante, id dapibus nulla venenatis sed. Suspendisse potenti. Nulla tincidunt metus eget elit commodo venenatis.  Suspendisse porttitor facilisis leo ac maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In vitae odio hendrerit quam pharetra euismod. Etiam accumsan lectus eget diam finibus cursus. Nam quis interdum sem. Duis ac consectetur tellus. Suspendisse tempor vitae tortor eget fringilla.Quisque ipsum lorem, fringilla a mollis nec, auctor quis magna. Mauris tincidunt tellus lacus, in interdum justo scelerisque id. Integer vitae efficitur diam. Curabitur venenatis auctor pretium. Suspendisse mattis sed nibh euismod pellentesque. Maecenas vulputate pellentesque nunc in varius. Maecenas nec felis cursus, maximus dui a, sagittis mauris. Morbi consequat dignissim erat, ultrices gravida lectus.",
    sentiment: "negative",
    sentimentrate: -67,
    plagiarizerate: 30.1,

    categories: "Crime",
    date: "Aug 8 2022 Tue",
    status: "For Review",
    remarks: "testing",
    action: "approved",
    author: "Lorem Ipsum",
    oversentiment: false,
    image:
      "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
  },
  {
    id: 1114,
    headline: "Lorem ipsum dolor sit amet",
    content:
      "Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Loerm euismod. Lorem ipsum dolor sit amet",
    sentiment: "positive",
    sentimentrate: 100,
    plagiarizerate: 30.1,
    categories: "Sports",
    date: "Aug 8 2022 Tue",
    status: "For Review",
    remarks: "testing",
    action: "approved",
    author: "Lorem Ipsum",
    oversentiment: false,
    image:
      "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
  },
  {
    id: 1115,
    headline: "Lorem ipsum dolor sit amet",
    content:
      "Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Loerm euismod. Lorem ipsum dolor sit amet",
    sentiment: "positive",
    sentimentrate: 100,
    plagiarizerate: 30.1,
    categories: "Sports",
    date: "Aug 8 2022 Tue",
    status: "For Review",
    remarks: "testing",
    action: "approved",
    author: "Lorem Ipsum",
    oversentiment: false,
    image:
      "http://santacruzlife.com/wp-content/uploads/2016/09/santa-cruz-10-7-2016.jpg",
  },
];
